In [2]:
import pandas as pd
import os,sys,re,glob
import numpy as np

In [3]:
df =pd.read_csv("modified_covid19_ts/merged_global2020-06-02.csv")
df.head()

,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
0,NaN,Afghanistan,33.0,65.0,2020-01-22,0,0
1,NaN,Afghanistan,33.0,65.0,2020-01-23,0,0
2,NaN,Afghanistan,33.0,65.0,2020-01-24,0,0
3,NaN,Afghanistan,33.0,65.0,2020-01-25,0,0
4,NaN,Afghanistan,33.0,65.0,2020-01-26,0,0

In [4]:
df["key"] = df.apply(lambda r: str(r["Province/State"]) +"_"+ str(r["Country/Region"]),axis=1)

In [5]:
df.head()

,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities,key
0,NaN,Afghanistan,33.0,65.0,2020-01-22,0,0,nan_Afghanistan
1,NaN,Afghanistan,33.0,65.0,2020-01-23,0,0,nan_Afghanistan
2,NaN,Afghanistan,33.0,65.0,2020-01-24,0,0,nan_Afghanistan
3,NaN,Afghanistan,33.0,65.0,2020-01-25,0,0,nan_Afghanistan
4,NaN,Afghanistan,33.0,65.0,2020-01-26,0,0,nan_Afghanistan

In [6]:
gf = {k:v for k,v in df.groupby("key")}

In [7]:
gff ={k:gf[k] for k in gf.keys() if gf[k].iloc[-1]["Fatalities"] > 100}

In [8]:
len(list(gf.keys())),len(list(gff.keys()))

(266, 73)

In [9]:
for k in gff.keys():
    gff[k]["Daily New Confirmed"] = gff[k]["ConfirmedCases"].diff(1).fillna(0.0)
    gff[k]["7 days New Confirmed"] = gff[k]["ConfirmedCases"].diff(7).fillna(0.0)
    gff[k]["14 days New Confirmed"] = gff[k]["ConfirmedCases"].diff(14).fillna(0.0)
    gff[k]["Total last 14 days ConfirmedCases"] = gff[k]["ConfirmedCases"].rolling(14).sum()

In [26]:
for k in gff.keys():
    gff[k]["Change 14 days"] = (gff[k]["Total last 14 days ConfirmedCases"] - gff[k]["Total last 14 days ConfirmedCases"].shift(14)).fillna(0.0)
    gff[k]["derivative Change 14 days"] = (gff[k]["Change 14 days"]/(1. + gff[k]["Change 14 days"].shift(14)) -1.).round(2)

In [34]:
import random
LL = list(gff.keys())
Lr = random.sample(LL,10)
count=0
AA=[]
for x in LL:
    d1 = gff[x].copy().fillna(0.0)
    d1 = d1[d1["Date"]>"2020-05-01"]
    d1 = d1.sort_values(by ="derivative Change 14 days")[["Date","key","Change 14 days","derivative Change 14 days"]]
    tail_d = list(d1.tail()["Date"])
    
    if not "2020-05-02" in tail_d and d1.iloc[-1]["derivative Change 14 days"]>0.5:
        count+=1
        print(d1.tail())
        AA.append(d1.iloc[-1]["key"])
        

print(count)
print(AA)

           Date              key  Change 14 days  derivative Change 14 days
111  2020-05-12  nan_Afghanistan         29646.0                       1.77
115  2020-05-16  nan_Afghanistan         38601.0                       1.80
114  2020-05-15  nan_Afghanistan         36204.0                       1.81
113  2020-05-14  nan_Afghanistan         33915.0                       1.81
112  2020-05-13  nan_Afghanistan         31778.0                       1.81
           Date          key  Change 14 days  derivative Change 14 days
380  2020-05-17  nan_Algeria         32283.0                       0.50
379  2020-05-16  nan_Algeria         31583.0                       0.51
378  2020-05-15  nan_Algeria         30818.0                       0.51
377  2020-05-14  nan_Algeria         30079.0                       0.51
376  2020-05-13  nan_Algeria         29381.0                       0.51
           Date            key  Change 14 days  derivative Change 14 days
919  2020-05-28  nan_Argentina         69558.0                       1.33
920  2020-05-29  nan_Argentina         74551.0                       1.41
921  2020-05-30  nan_Argentina         79836.0                       1.49
922  2020-05-31  nan_Argentina         85334.0                       1.55
923  2020-06-01  nan_Argentina         90894.0                       1.60
            Date          key  Change 14 days  derivative Change 14 days
1036  2020-05-13  nan_Armenia         18569.0                       1.15
1052  2020-05-29  nan_Armenia         44048.0                       1.16
1053  2020-05-30  nan_Armenia         46682.0                       1.18
1055  2020-06-01  nan_Armenia         51759.0                       1.20
1054  2020-05-31  nan_Armenia         49406.0                       1.21
            Date          key  Change 14 days  derivative Change 14 days
3545  2020-05-14  nan_Bolivia         20398.0                       1.80
3547  2020-05-16  nan_Bolivia         23361.0                       1.80
3539  2020-05-08  nan_Bolivia         13313.0                       1.82
3538  2020-05-07  nan_Bolivia         12393.0                       1.83
3546  2020-05-15  nan_Bolivia         21982.0                       1.85
            Date         key  Change 14 days  derivative Change 14 days
3807  2020-05-12  nan_Brazil       1093419.0                       1.44
3806  2020-05-11  nan_Brazil       1036413.0                       1.47
3803  2020-05-08  nan_Brazil        861450.0                       1.47
3805  2020-05-10  nan_Brazil        978281.0                       1.48
3804  2020-05-09  nan_Brazil        919590.0                       1.48
            Date           key  Change 14 days  derivative Change 14 days
4067  2020-05-08  nan_Bulgaria          9706.0                       0.81
4063  2020-05-04  nan_Bulgaria          8760.0                       0.81
4064  2020-05-05  nan_Bulgaria          9091.0                       0.86
4065  2020-05-06  nan_Bulgaria          9414.0                       0.89
4066  2020-05-07  nan_Bulgaria          9667.0                       0.90
            Date           key  Change 14 days  derivative Change 14 days
4615  2020-05-28  nan_Cameroon         26304.0                       0.95
4616  2020-05-29  nan_Cameroon         27362.0                       0.97
4617  2020-05-30  nan_Cameroon         29133.0                       1.10
4618  2020-05-31  nan_Cameroon         30904.0                       1.23
4619  2020-06-01  nan_Cameroon         32347.0                       1.26
            Date        key  Change 14 days  derivative Change 14 days
6457  2020-05-22  nan_Chile        326093.0                       1.63
6458  2020-05-23  nan_Chile        349906.0                       1.64
6459  2020-05-24  nan_Chile        374607.0                       1.64
6460  2020-05-25  nan_Chile        402291.0                       1.65
6461  2020-05-26  nan_Chile        431175.0                       1.65
             Date           key  Change 14 days  derivative Change 14 days
10939  2020-05-16  nan_Colombia         79070.0                       1.05
10943  2020-05-20  nan_Colombia         95409.0                       1.06
10940  2020-05-17  nan_Colombia         83100.0                       1.07
10942  2020-05-19  nan_Colombia         91284.0                       1.08
10941  2020-05-18  nan_Colombia         87426.0                       1.09
             Date          key  Change 14 days  derivative Change 14 days
12906  2020-05-03  nan_Ecuador        194213.0                       1.93
12907  2020-05-04  nan_Ecuador        209585.0                       1.99
12908  2020-05-05  nan_Ecuador        224417.0                       2.03
12909  2020-05-06  nan_Ecuador        239048.0                       2.10
12910  2020-05-07  nan_Ecuador        251945.0                       2.16
             Date        key  Change 14 days  derivative Change 14 days
13051  2020-05-16  nan_Egypt         63755.0                       0.84
13050  2020-05-15  nan_Egypt         61390.0                       0.84
13049  2020-05-14  nan_Egypt         59108.0                       0.84
13053  2020-05-18  nan_Egypt         68669.0                       0.84
13067  2020-06-01  nan_Egypt        127713.0                       0.86
             Date            key  Change 14 days  derivative Change 14 days
16362  2020-05-27  nan_Guatemala         24258.0                       2.40
16365  2020-05-30  nan_Guatemala         30035.0                       2.40
16363  2020-05-28  nan_Guatemala         26169.0                       2.42
16366  2020-05-31  nan_Guatemala         32299.0                       2.42
16364  2020-05-29  nan_Guatemala         28134.0                       2.43
             Date           key  Change 14 days  derivative Change 14 days
17008  2020-05-13  nan_Honduras         13499.0                       3.32
17012  2020-05-17  nan_Honduras         18005.0                       3.35
17009  2020-05-14  nan_Honduras         14701.0                       3.51
17011  2020-05-16  nan_Honduras         16997.0                       3.52
17010  2020-05-15  nan_Honduras         15995.0                       3.70
             Date       key  Change 14 days  derivative Change 14 days
17682  2020-05-27  nan_Iran        353991.0                       0.53
17686  2020-05-31  nan_Iran        389566.0                       0.54
17683  2020-05-28  nan_Iran        363414.0                       0.55
17685  2020-05-30  nan_Iran        381072.0                       0.55
17684  2020-05-29  nan_Iran        372458.0                       0.56
             Date       key  Change 14 days  derivative Change 14 days
17805  2020-05-18  nan_Iraq         13742.0                       0.75
17816  2020-05-29  nan_Iraq         22617.0                       0.79
17817  2020-05-30  nan_Iraq         24495.0                       0.89
17818  2020-05-31  nan_Iraq         26422.0                       0.99
17819  2020-06-01  nan_Iraq         28528.0                       1.08
             Date               key  Change 14 days  derivative Change 14 days
19005  2020-05-30  nan_Korea, South          4563.0                       0.88
19004  2020-05-29  nan_Korea, South          4402.0                       0.90
19001  2020-05-26  nan_Korea, South          3988.0                       0.93
19003  2020-05-28  nan_Korea, South          4255.0                       0.93
19002  2020-05-27  nan_Korea, South          4115.0                       0.94
             Date         key  Change 14 days  derivative Change 14 days
19124  2020-05-17  nan_Kuwait         85761.0                       2.03
19128  2020-05-21  nan_Kuwait        115239.0                       2.03
19127  2020-05-20  nan_Kuwait        107365.0                       2.04
19126  2020-05-19  nan_Kuwait        100127.0                       2.07
19125  2020-05-18  nan_Kuwait         92891.0                       2.07
             Date          key  Change 14 days  derivative Change 14 days
22939  2020-05-04  nan_Nigeria         16860.0                       3.55
22943  2020-05-08  nan_Nigeria         24288.0                       3.58
22942  2020-05-07  nan_Nigeria         22261.0                       3.68
22941  2020-05-06  nan_Nigeria         20409.0                       3.77
22940  2020-05-05  nan_Nigeria         18734.0                       3.79
             Date           key  Change 14 days  derivative Change 14 days
23467  2020-05-04  nan_Pakistan        124111.0                       1.24
23471  2020-05-08  nan_Pakistan        153322.0                       1.26
23468  2020-05-05  nan_Pakistan        131065.0                       1.26
23470  2020-05-07  nan_Pakistan        146072.0                       1.29
23469  2020-05-06  nan_Pakistan        139249.0                       1.30

             Date               key  Change 14 days  derivative Change 14 days
26523  2020-05-24  nan_South Africa        126015.0                       1.39
26507  2020-05-08  nan_South Africa         46943.0                       1.40
26504  2020-05-05  nan_South Africa         39842.0                       1.41
26506  2020-05-07  nan_South Africa         44485.0                       1.44
26505  2020-05-06  nan_South Africa         42225.0                       1.45
21
['nan_Afghanistan', 'nan_Algeria', 'nan_Argentina', 'nan_Armenia', 'nan_Bolivia', 'nan_Brazil', 'nan_Bulgaria', 'nan_Cameroon', 'nan_Chile', 'nan_Colombia', 'nan_Ecuador', 'nan_Egypt', 'nan_Guatemala', 'nan_Honduras', 'nan_Iran', 'nan_Iraq', 'nan_Korea, South', 'nan_Kuwait', 'nan_Nigeria', 'nan_Pakistan', 'nan_South Africa']

In [1]:
for k in AA:
    print(k.split("_")[1],gf[k].iloc[-30]["Fatalities"],gf[k].iloc[-1]["Fatalities"])

NameError: name 'AA' is not defined